// <auto-generated />
namespace zxc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init05));
        
        string IMigrationMetadata.Id
        {
            get { return "202206072228439_init0.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
