// <auto-generated />
namespace zxc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class qw2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qw2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206092202225_qw2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
